export const ASSISTANT_REQUESTS_SCOPE_V1: string = process.env.ASSISTANT_REQUESTS_SCOPE_V1;
export const ASSISTANT_REQUESTS_SCOPE_READ: string = process.env.ASSISTANT_REQUESTS_SCOPE_READ;
export const ASSISTANT_REQUESTS_SCOPE_WRITE: string = process.env.ASSISTANT_REQUESTS_SCOPE_WRITE;
