import { ASSISTANT_REQUESTS_SCOPE_V1, ASSISTANT_REQUESTS_SCOPE_READ, ASSISTANT_REQUESTS_SCOPE_WRITE } from './constants';

export const getScopes = (): string[] => [ASSISTANT_REQUESTS_SCOPE_V1, ASSISTANT_REQUESTS_SCOPE_READ, ASSISTANT_REQUESTS_SCOPE_WRITE];
